# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing with clojure, read the docs:
# https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    docker: 
      - image: circleci/clojure:lein-2.9.5
      - working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bootstrap Babashka
          command: |
            curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
            chmod +x install
	    sudo ./install
      - run:
          name: run tests
          command: bb test.clj

workflows:
  setup:
    jobs:
      - test
